apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mirth-cluster
  labels:
    app: mysql
    app.kubernetes.io/part-of: mirth-connect
spec:
  type: ExternalName
  externalName: mysql.mirth-infra.svc.cluster.local
