apiVersion: v1
kind: ConfigMap
metadata:
  name: node-mirth-config
  namespace: mirth-cluster
  labels:
    app: node-mirth
    app.kubernetes.io/part-of: mirth-connect
data:
  NODE_ENV: "production"
  MIRTH_CLUSTER_HEARTBEAT_INTERVAL: "10000"
  MIRTH_CLUSTER_HEARTBEAT_TIMEOUT: "30000"
  MIRTH_CLUSTER_SEQUENCE_BLOCK: "100"
