apiVersion: v1
kind: Service
metadata:
  name: sftp
  namespace: mirth-takeover
  labels:
    app: sftp
    app.kubernetes.io/part-of: mirth-connect
spec:
  type: ExternalName
  externalName: sftp.mirth-infra.svc.cluster.local
