apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mirth-standalone
resources:
  - namespace.yaml
  - mysql-standalone.yaml
  - node-mirth-deployment.yaml
  - node-mirth-service.yaml
  - node-mirth-configmap.yaml
  - otel-collector.yaml
