apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-mirth
  namespace: mirth-infra
  labels:
    app: java-mirth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-mirth
  template:
    metadata:
      labels:
        app: java-mirth
    spec:
      containers:
        - name: java-mirth
          image: nextgenhealthcare/connect:3.9
          imagePullPolicy: Never
          ports:
            - containerPort: 8443
              name: https
            - containerPort: 6661
              name: mllp
          env:
            - name: DATABASE
              value: mysql
            - name: DATABASE_URL
              value: jdbc:mysql://mysql:3306/mirthdb
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          startupProbe:
            httpGet:
              path: /api/server/version
              port: 8443
              scheme: HTTPS
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/server/version
              port: 8443
              scheme: HTTPS
            periodSeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/server/version
              port: 8443
              scheme: HTTPS
            periodSeconds: 60
            timeoutSeconds: 5
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 2Gi
              cpu: "2"
