apiVersion: v1
kind: Service
metadata:
  name: java-mirth
  namespace: mirth-infra
  labels:
    app: java-mirth
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: https
    - port: 6661
      targetPort: 6661
      protocol: TCP
      name: mllp
  selector:
    app: java-mirth
