apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mirth-infra
resources:
  - namespace.yaml
  - mysql-secret.yaml
  - mysql-configmap.yaml
  - mysql-statefulset.yaml
  - mysql-service.yaml
  - java-mirth-deployment.yaml
  - java-mirth-service.yaml
  - mailhog-deployment.yaml
  - mailhog-service.yaml
  - activemq-deployment.yaml
  - activemq-service.yaml
  # Images not yet pulled:
  # - castlemock-deployment.yaml
  # - castlemock-service.yaml
  # - orthanc-deployment.yaml
  # - orthanc-service.yaml
  # - sftp-deployment.yaml
  # - sftp-service.yaml
