apiVersion: v1
kind: Service
metadata:
  name: sftp
  namespace: mirth-infra
  labels:
    app: sftp
spec:
  type: ClusterIP
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: sftp
  selector:
    app: sftp
